SRC1 = pf.c
SRC2 = page_fault_algorithms.c
SRC3 = queue.c
SRC4 = linked_list.c
EXE = $(SRC1:.c=.e)
CFLAGS = -g
HFILES = page_fault_algorithms.h queue.h linked_list.h 

all : 
	gcc $(CFLAGS) $(SRC1) $(SRC2) $(SRC3) $(SRC4) $(HFILES) -o $(EXE) 
